spring.application.name=school-management
spring.datasource.url=jdbc:postgresql://localhost:5432/school_db
spring.datasource.username=school_user
spring.datasource.password=school_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true